### ISSUE TITLE
Broken DVD Xpress patch links

### ISSUE THREAD

**Issue by refi64** [jbuchbinder/jbuchbinder.com#1]
http://jbuchbinder.com/2010/03/25/updated-linux-support-for-ads-dvd-xpress-dx2/

[Linux now has the go7007 driver built-in](https://github.com/torvalds/linux/tree/master/drivers/media/usb/go7007), so I wanted to see if I could get your patch working again, but there's no link. I'm guessing it was a victim of the Octopress -> Hugo conversion?

**Comment by jbuchbinder** [comment]
The link is here:

http://jbuchbinder.com//images/2010/03/wis-go7007-linux-098-5-20100325.diff

I'll readjust the page to have the appropriate link -- thanks!
